### ISSUE TITLE
Deploy from mac OS

### ISSUE THREAD

**Issue by raslasarslas** [Mercateo/serverless-image-processor#24]
Hi, this project work perfectly when i deploy it from ubuntu using serverless, but not work from mac OS, i had this error on lambda logs ``module initialization error``.  is it any way to do to make it deployement work from macOS?

**Comment by otbe** [comment]
Thanks for using this project :)

It should work for all kinds of OS because webpack will bundle the precompiled version of sharp (located in `compiled/`). The example deployment is done via mac OS too :)

Did you updated webpack or something else?
Can you verfiy that the packaged module (zip file in `.serverless/`) contains the `compiled/` folder from this project (same files)?
